// Generated by rstantools.  Do not edit by hand.

/*
    rbioacc is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    rbioacc is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with rbioacc.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#ifndef USE_STANC3
#define USE_STANC3
#endif
#include <rstan/rstaninc.hpp>
// Code generated by stanc v2.26.1-4-gd72b68b7-dirty
#include <stan/model/model_header.hpp>
namespace model_TK_predict_namespace {
inline void validate_positive_index(const char* var_name, const char* expr,
                                    int val) {
  if (val < 1) {
    std::stringstream msg;
    msg << "Found dimension size less than one in simplex declaration"
        << "; variable=" << var_name << "; dimension size expression=" << expr
        << "; expression value=" << val;
    std::string msg_str(msg.str());
    throw std::invalid_argument(msg_str.c_str());
  }
}
inline void validate_unit_vector_index(const char* var_name, const char* expr,
                                       int val) {
  if (val <= 1) {
    std::stringstream msg;
    if (val == 1) {
      msg << "Found dimension size one in unit vector declaration."
          << " One-dimensional unit vector is discrete"
          << " but the target distribution must be continuous."
          << " variable=" << var_name << "; dimension size expression=" << expr;
    } else {
      msg << "Found dimension size less than one in unit vector declaration"
          << "; variable=" << var_name << "; dimension size expression=" << expr
          << "; expression value=" << val;
    }
    std::string msg_str(msg.str());
    throw std::invalid_argument(msg_str.c_str());
  }
}
using std::istream;
using std::string;
using std::stringstream;
using std::vector;
using std::pow;
using stan::io::dump;
using stan::math::lgamma;
using stan::model::model_base_crtp;
using stan::model::rvalue;
using stan::model::cons_list;
using stan::model::index_uni;
using stan::model::index_max;
using stan::model::index_min;
using stan::model::index_min_max;
using stan::model::index_multi;
using stan::model::index_omni;
using stan::model::nil_index_list;
using namespace stan::math;
using stan::math::pow; 
stan::math::profile_map profiles__;
static int current_statement__= 0;
static const std::vector<string> locations_array__ = {" (found before start of program)",
                                                      " (in 'TK_predict', line 162, column 2 to column 36)",
                                                      " (in 'TK_predict', line 163, column 2 to column 35)",
                                                      " (in 'TK_predict', line 164, column 2 to column 37)",
                                                      " (in 'TK_predict', line 166, column 2 to column 29)",
                                                      " (in 'TK_predict', line 167, column 2 to column 29)",
                                                      " (in 'TK_predict', line 168, column 2 to column 29)",
                                                      " (in 'TK_predict', line 169, column 2 to column 30)",
                                                      " (in 'TK_predict', line 170, column 2 to column 19)",
                                                      " (in 'TK_predict', line 171, column 2 to column 19)",
                                                      " (in 'TK_predict', line 172, column 2 to column 19)",
                                                      " (in 'TK_predict', line 174, column 2 to column 30)",
                                                      " (in 'TK_predict', line 175, column 2 to column 32)",
                                                      " (in 'TK_predict', line 179, column 6 to column 70)",
                                                      " (in 'TK_predict', line 178, column 21 to line 180, column 5)",
                                                      " (in 'TK_predict', line 178, column 4 to line 180, column 5)",
                                                      " (in 'TK_predict', line 177, column 19 to line 181, column 3)",
                                                      " (in 'TK_predict', line 177, column 2 to line 181, column 3)",
                                                      " (in 'TK_predict', line 185, column 6 to column 33)",
                                                      " (in 'TK_predict', line 184, column 21 to line 186, column 5)",
                                                      " (in 'TK_predict', line 184, column 4 to line 186, column 5)",
                                                      " (in 'TK_predict', line 191, column 8 to column 35)",
                                                      " (in 'TK_predict', line 190, column 12 to line 192, column 7)",
                                                      " (in 'TK_predict', line 189, column 9 to column 20)",
                                                      " (in 'TK_predict', line 188, column 28 to line 190, column 7)",
                                                      " (in 'TK_predict', line 188, column 6 to line 192, column 7)",
                                                      " (in 'TK_predict', line 187, column 21 to line 193, column 5)",
                                                      " (in 'TK_predict', line 187, column 4 to line 193, column 5)",
                                                      " (in 'TK_predict', line 195, column 6 to column 33)",
                                                      " (in 'TK_predict', line 196, column 6 to column 35)",
                                                      " (in 'TK_predict', line 194, column 21 to line 197, column 5)",
                                                      " (in 'TK_predict', line 194, column 4 to line 197, column 5)",
                                                      " (in 'TK_predict', line 200, column 6 to column 45)",
                                                      " (in 'TK_predict', line 201, column 6 to column 36)",
                                                      " (in 'TK_predict', line 198, column 21 to line 202, column 5)",
                                                      " (in 'TK_predict', line 198, column 4 to line 202, column 5)",
                                                      " (in 'TK_predict', line 204, column 8 to column 40)",
                                                      " (in 'TK_predict', line 203, column 21 to line 205, column 5)",
                                                      " (in 'TK_predict', line 203, column 4 to line 205, column 5)",
                                                      " (in 'TK_predict', line 209, column 6 to column 71)",
                                                      " (in 'TK_predict', line 213, column 11 to line 215, column 14)",
                                                      " (in 'TK_predict', line 212, column 25 to line 216, column 9)",
                                                      " (in 'TK_predict', line 212, column 8 to line 216, column 9)",
                                                      " (in 'TK_predict', line 211, column 19 to line 217, column 7)",
                                                      " (in 'TK_predict', line 211, column 6 to line 217, column 7)",
                                                      " (in 'TK_predict', line 207, column 23 to line 218, column 5)",
                                                      " (in 'TK_predict', line 207, column 4 to line 218, column 5)",
                                                      " (in 'TK_predict', line 222, column 6 to column 96)",
                                                      " (in 'TK_predict', line 226, column 8 to line 230, column 13)",
                                                      " (in 'TK_predict', line 225, column 25 to line 231, column 9)",
                                                      " (in 'TK_predict', line 225, column 8 to line 231, column 9)",
                                                      " (in 'TK_predict', line 224, column 19 to line 232, column 7)",
                                                      " (in 'TK_predict', line 224, column 6 to line 232, column 7)",
                                                      " (in 'TK_predict', line 220, column 31 to line 233, column 5)",
                                                      " (in 'TK_predict', line 220, column 4 to line 233, column 5)",
                                                      " (in 'TK_predict', line 237, column 8 to column 80)",
                                                      " (in 'TK_predict', line 236, column 23 to line 238, column 7)",
                                                      " (in 'TK_predict', line 236, column 6 to line 238, column 7)",
                                                      " (in 'TK_predict', line 235, column 18 to line 239, column 5)",
                                                      " (in 'TK_predict', line 235, column 4 to line 239, column 5)",
                                                      " (in 'TK_predict', line 244, column 6 to column 66)",
                                                      " (in 'TK_predict', line 247, column 8 to column 71)",
                                                      " (in 'TK_predict', line 246, column 23 to line 248, column 7)",
                                                      " (in 'TK_predict', line 246, column 6 to line 248, column 7)",
                                                      " (in 'TK_predict', line 242, column 21 to line 249, column 5)",
                                                      " (in 'TK_predict', line 242, column 4 to line 249, column 5)",
                                                      " (in 'TK_predict', line 252, column 8 to column 68)",
                                                      " (in 'TK_predict', line 251, column 23 to line 253, column 7)",
                                                      " (in 'TK_predict', line 251, column 6 to line 253, column 7)",
                                                      " (in 'TK_predict', line 250, column 18 to line 254, column 5)",
                                                      " (in 'TK_predict', line 250, column 4 to line 254, column 5)",
                                                      " (in 'TK_predict', line 183, column 23 to line 255, column 3)",
                                                      " (in 'TK_predict', line 183, column 2 to line 255, column 3)",
                                                      " (in 'TK_predict', line 129, column 2 to column 21)",
                                                      " (in 'TK_predict', line 130, column 9 to column 14)",
                                                      " (in 'TK_predict', line 130, column 2 to column 20)",
                                                      " (in 'TK_predict', line 132, column 2 to column 22)",
                                                      " (in 'TK_predict', line 133, column 9 to column 15)",
                                                      " (in 'TK_predict', line 133, column 2 to column 21)",
                                                      " (in 'TK_predict', line 135, column 2 to column 22)",
                                                      " (in 'TK_predict', line 136, column 9 to column 15)",
                                                      " (in 'TK_predict', line 136, column 17 to column 22)",
                                                      " (in 'TK_predict', line 136, column 2 to column 30)",
                                                      " (in 'TK_predict', line 138, column 2 to column 24)",
                                                      " (in 'TK_predict', line 139, column 2 to column 22)",
                                                      " (in 'TK_predict', line 140, column 2 to column 20)",
                                                      " (in 'TK_predict', line 141, column 2 to column 18)",
                                                      " (in 'TK_predict', line 143, column 2 to column 22)",
                                                      " (in 'TK_predict', line 144, column 2 to column 22)",
                                                      " (in 'TK_predict', line 145, column 2 to column 16)",
                                                      " (in 'TK_predict', line 146, column 9 to column 18)",
                                                      " (in 'TK_predict', line 146, column 20 to column 25)",
                                                      " (in 'TK_predict', line 146, column 2 to column 36)",
                                                      " (in 'TK_predict', line 147, column 9 to column 18)",
                                                      " (in 'TK_predict', line 147, column 20 to column 25)",
                                                      " (in 'TK_predict', line 147, column 2 to column 36)",
                                                      " (in 'TK_predict', line 148, column 9 to column 18)",
                                                      " (in 'TK_predict', line 148, column 20 to column 25)",
                                                      " (in 'TK_predict', line 148, column 2 to column 36)",
                                                      " (in 'TK_predict', line 149, column 9 to column 18)",
                                                      " (in 'TK_predict', line 149, column 20 to column 25)",
                                                      " (in 'TK_predict', line 149, column 2 to column 37)",
                                                      " (in 'TK_predict', line 150, column 8 to column 17)",
                                                      " (in 'TK_predict', line 150, column 2 to column 27)",
                                                      " (in 'TK_predict', line 151, column 8 to column 17)",
                                                      " (in 'TK_predict', line 151, column 2 to column 27)",
                                                      " (in 'TK_predict', line 152, column 8 to column 17)",
                                                      " (in 'TK_predict', line 152, column 19 to column 24)",
                                                      " (in 'TK_predict', line 152, column 2 to column 53)",
                                                      " (in 'TK_predict', line 153, column 18 to column 27)",
                                                      " (in 'TK_predict', line 153, column 29 to column 34)",
                                                      " (in 'TK_predict', line 153, column 2 to column 51)",
                                                      " (in 'TK_predict', line 154, column 8 to column 17)",
                                                      " (in 'TK_predict', line 154, column 19 to column 28)",
                                                      " (in 'TK_predict', line 154, column 2 to column 50)",
                                                      " (in 'TK_predict', line 155, column 8 to column 17)",
                                                      " (in 'TK_predict', line 155, column 19 to column 27)",
                                                      " (in 'TK_predict', line 155, column 2 to column 46)",
                                                      " (in 'TK_predict', line 162, column 8 to column 13)",
                                                      " (in 'TK_predict', line 162, column 14 to column 19)",
                                                      " (in 'TK_predict', line 163, column 8 to column 13)",
                                                      " (in 'TK_predict', line 163, column 14 to column 19)",
                                                      " (in 'TK_predict', line 164, column 9 to column 14)",
                                                      " (in 'TK_predict', line 164, column 16 to column 21)",
                                                      " (in 'TK_predict', line 166, column 18 to column 23)",
                                                      " (in 'TK_predict', line 167, column 18 to column 23)",
                                                      " (in 'TK_predict', line 168, column 18 to column 23)",
                                                      " (in 'TK_predict', line 169, column 18 to column 23)",
                                                      " (in 'TK_predict', line 170, column 9 to column 14)",
                                                      " (in 'TK_predict', line 171, column 9 to column 14)",
                                                      " (in 'TK_predict', line 172, column 9 to column 14)",
                                                      " (in 'TK_predict', line 174, column 9 to column 14)",
                                                      " (in 'TK_predict', line 174, column 15 to column 20)",
                                                      " (in 'TK_predict', line 175, column 9 to column 14)",
                                                      " (in 'TK_predict', line 175, column 15 to column 20)",
                                                      " (in 'TK_predict', line 5, column 2 to column 13)",
                                                      " (in 'TK_predict', line 13, column 6 to column 15)",
                                                      " (in 'TK_predict', line 12, column 24 to line 14, column 5)",
                                                      " (in 'TK_predict', line 12, column 4 to line 14, column 5)",
                                                      " (in 'TK_predict', line 15, column 4 to column 14)",
                                                      " (in 'TK_predict', line 11, column 9 to line 16, column 3)",
                                                      " (in 'TK_predict', line 10, column 4 to column 14)",
                                                      " (in 'TK_predict', line 9, column 39 to line 11, column 3)",
                                                      " (in 'TK_predict', line 9, column 9 to line 16, column 3)",
                                                      " (in 'TK_predict', line 7, column 4 to column 30)",
                                                      " (in 'TK_predict', line 8, column 4 to column 14)",
                                                      " (in 'TK_predict', line 6, column 18 to line 9, column 3)",
                                                      " (in 'TK_predict', line 6, column 2 to line 16, column 3)",
                                                      " (in 'TK_predict', line 4, column 33 to line 17, column 1)",
                                                      " (in 'TK_predict', line 24, column 4 to column 16)",
                                                      " (in 'TK_predict', line 23, column 8 to line 25, column 3)",
                                                      " (in 'TK_predict', line 21, column 4 to column 33)",
                                                      " (in 'TK_predict', line 22, column 4 to column 90)",
                                                      " (in 'TK_predict', line 20, column 36 to line 23, column 3)",
                                                      " (in 'TK_predict', line 20, column 2 to line 25, column 3)",
                                                      " (in 'TK_predict', line 19, column 48 to line 26, column 1)",
                                                      " (in 'TK_predict', line 37, column 2 to column 27)",
                                                      " (in 'TK_predict', line 38, column 2 to column 22)",
                                                      " (in 'TK_predict', line 39, column 2 to column 22)",
                                                      " (in 'TK_predict', line 40, column 2 to column 22)",
                                                      " (in 'TK_predict', line 41, column 2 to column 22)",
                                                      " (in 'TK_predict', line 43, column 8 to column 13)",
                                                      " (in 'TK_predict', line 43, column 2 to column 41)",
                                                      " (in 'TK_predict', line 44, column 8 to column 13)",
                                                      " (in 'TK_predict', line 44, column 2 to column 57)",
                                                      " (in 'TK_predict', line 45, column 8 to column 13)",
                                                      " (in 'TK_predict', line 45, column 2 to column 69)",
                                                      " (in 'TK_predict', line 46, column 8 to column 13)",
                                                      " (in 'TK_predict', line 46, column 2 to column 82)",
                                                      " (in 'TK_predict', line 49, column 8 to column 15)",
                                                      " (in 'TK_predict', line 49, column 2 to column 28)",
                                                      " (in 'TK_predict', line 51, column 2 to column 22)",
                                                      " (in 'TK_predict', line 53, column 9 to column 19)",
                                                      " (in 'TK_predict', line 53, column 2 to column 65)",
                                                      " (in 'TK_predict', line 57, column 9 to column 19)",
                                                      " (in 'TK_predict', line 57, column 2 to column 91)",
                                                      " (in 'TK_predict', line 60, column 2 to column 10)",
                                                      " (in 'TK_predict', line 61, column 2 to column 10)",
                                                      " (in 'TK_predict', line 62, column 2 to column 10)",
                                                      " (in 'TK_predict', line 67, column 4 to column 17)",
                                                      " (in 'TK_predict', line 66, column 8 to line 68, column 3)",
                                                      " (in 'TK_predict', line 65, column 4 to column 11)",
                                                      " (in 'TK_predict', line 64, column 16 to line 66, column 3)",
                                                      " (in 'TK_predict', line 64, column 2 to line 68, column 3)",
                                                      " (in 'TK_predict', line 69, column 2 to column 15)",
                                                      " (in 'TK_predict', line 73, column 2 to column 50)",
                                                      " (in 'TK_predict', line 84, column 4 to column 32)",
                                                      " (in 'TK_predict', line 82, column 8 to line 85, column 3)",
                                                      " (in 'TK_predict', line 81, column 4 to column 34)",
                                                      " (in 'TK_predict', line 79, column 15 to line 82, column 3)",
                                                      " (in 'TK_predict', line 79, column 2 to line 85, column 3)",
                                                      " (in 'TK_predict', line 88, column 6 to column 47)",
                                                      " (in 'TK_predict', line 87, column 25 to line 89, column 5)",
                                                      " (in 'TK_predict', line 87, column 4 to line 89, column 5)",
                                                      " (in 'TK_predict', line 86, column 15 to line 90, column 3)",
                                                      " (in 'TK_predict', line 86, column 2 to line 90, column 3)",
                                                      " (in 'TK_predict', line 91, column 2 to column 16)",
                                                      " (in 'TK_predict', line 33, column 30 to line 92, column 1)"};
template <typename T0__, typename T1__>
int
findfirst(const T0__& t, const T1__& xt_arg__, std::ostream* pstream__) {
  using local_scalar_t__ = stan::promote_args_t<T0__,
          stan::value_type_t<T1__>>;
  const auto& xt = to_ref(xt_arg__);
  const static bool propto__ = true;
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  (void) DUMMY_VAR__;  // suppress unused var warning
  
  try {
    int i;
    i = std::numeric_limits<int>::min();
    
    current_statement__ = 135;
    i = 0;
    current_statement__ = 147;
    if (logical_eq(t, max(xt))) {
      current_statement__ = 144;
      i = (num_elements(xt) - 1);
      current_statement__ = 145;
      return i;
    } else {
      current_statement__ = 143;
      if ((primitive_value(logical_lt(t, min(xt))) || primitive_value(
          logical_gt(t, max(xt))))) {
        current_statement__ = 141;
        return i;
      } else {
        current_statement__ = 138;
        while (logical_gte(t, xt[((i + 1) - 1)])) {
          current_statement__ = 136;
          i = (i + 1);
        }
        current_statement__ = 139;
        return i;
      }
    }
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
  }
  
}
struct findfirst_functor__ {
template <typename T0__, typename T1__>
int
operator()(const T0__& t, const T1__& xt, std::ostream* pstream__)  const 
{
return findfirst(t, xt, pstream__);
}
};
template <typename T0__, typename T1__, typename T2__>
stan::promote_args_t<T0__, stan::value_type_t<T1__>,
stan::value_type_t<T2__>>
interpolate(const T0__& x, const T1__& xpt_arg__, const T2__& ypt_arg__,
            std::ostream* pstream__) {
  using local_scalar_t__ = stan::promote_args_t<T0__,
          stan::value_type_t<T1__>,
          stan::value_type_t<T2__>>;
  const auto& xpt = to_ref(xpt_arg__);
  const auto& ypt = to_ref(ypt_arg__);
  const static bool propto__ = true;
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  (void) DUMMY_VAR__;  // suppress unused var warning
  
  try {
    current_statement__ = 154;
    if ((primitive_value(logical_gte(x, min(xpt))) && primitive_value(
        logical_lte(x, max(xpt))))) {
      int idx;
      idx = std::numeric_limits<int>::min();
      
      current_statement__ = 151;
      idx = findfirst(x, xpt, pstream__);
      current_statement__ = 152;
      return (ypt[(idx - 1)] +
               (((x - xpt[(idx - 1)]) *
                  (ypt[((idx + 1) - 1)] - ypt[(idx - 1)])) /
                 (xpt[((idx + 1) - 1)] - xpt[(idx - 1)])));
    } else {
      current_statement__ = 149;
      return 0.0;
    }
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
  }
  
}
struct interpolate_functor__ {
template <typename T0__, typename T1__, typename T2__>
stan::promote_args_t<T0__, stan::value_type_t<T1__>,
stan::value_type_t<T2__>>
operator()(const T0__& x, const T1__& xpt, const T2__& ypt,
           std::ostream* pstream__)  const 
{
return interpolate(x, xpt, ypt, pstream__);
}
};
template <typename T0__, typename T1__, typename T2__, typename T3__>
std::vector<stan::promote_args_t<T0__, T1__, T2__,
T3__>>
odeTK(const T0__& t, const std::vector<T1__>& y,
      const std::vector<T2__>& theta, const std::vector<T3__>& x_r,
      const std::vector<int>& x_i, std::ostream* pstream__) {
  using local_scalar_t__ = stan::promote_args_t<T0__, T1__, T2__, T3__>;
  const static bool propto__ = true;
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  (void) DUMMY_VAR__;  // suppress unused var warning
  
  try {
    int lentp_rmNA;
    lentp_rmNA = std::numeric_limits<int>::min();
    
    current_statement__ = 156;
    lentp_rmNA = x_i[(1 - 1)];
    int lentp;
    lentp = std::numeric_limits<int>::min();
    
    current_statement__ = 157;
    lentp = x_i[(2 - 1)];
    int n_exp;
    n_exp = std::numeric_limits<int>::min();
    
    current_statement__ = 158;
    n_exp = x_i[(3 - 1)];
    int n_out;
    n_out = std::numeric_limits<int>::min();
    
    current_statement__ = 159;
    n_out = x_i[(4 - 1)];
    int n_met;
    n_met = std::numeric_limits<int>::min();
    
    current_statement__ = 160;
    n_met = x_i[(5 - 1)];
    current_statement__ = 161;
    validate_non_negative_index("ku", "n_exp", n_exp);
    std::vector<local_scalar_t__> ku;
    ku = std::vector<local_scalar_t__>(n_exp, DUMMY_VAR__);
    
    current_statement__ = 162;
    assign(ku, nil_index_list(),
      rvalue(theta, cons_list(index_min_max(1, n_exp), nil_index_list()),
        "theta"), "assigning variable ku");
    current_statement__ = 163;
    validate_non_negative_index("ke", "n_out", n_out);
    std::vector<local_scalar_t__> ke;
    ke = std::vector<local_scalar_t__>(n_out, DUMMY_VAR__);
    
    current_statement__ = 164;
    assign(ke, nil_index_list(),
      rvalue(theta,
        cons_list(index_min_max((n_exp + 1), (n_exp + n_out)),
          nil_index_list()), "theta"), "assigning variable ke");
    current_statement__ = 165;
    validate_non_negative_index("km", "n_met", n_met);
    std::vector<local_scalar_t__> km;
    km = std::vector<local_scalar_t__>(n_met, DUMMY_VAR__);
    
    current_statement__ = 166;
    assign(km, nil_index_list(),
      rvalue(theta,
        cons_list(
          index_min_max(((n_exp + n_out) + 1), ((n_exp + n_out) + n_met)),
          nil_index_list()), "theta"), "assigning variable km");
    current_statement__ = 167;
    validate_non_negative_index("kem", "n_met", n_met);
    std::vector<local_scalar_t__> kem;
    kem = std::vector<local_scalar_t__>(n_met, DUMMY_VAR__);
    
    current_statement__ = 168;
    assign(kem, nil_index_list(),
      rvalue(theta,
        cons_list(
          index_min_max((((n_exp + n_out) + n_met) + 1), (((n_exp + n_out) +
                                                            n_met) + n_met)),
          nil_index_list()), "theta"), "assigning variable kem");
    current_statement__ = 169;
    validate_non_negative_index("dydt", "1 + n_met", (1 + n_met));
    std::vector<local_scalar_t__> dydt;
    dydt = std::vector<local_scalar_t__>((1 + n_met), DUMMY_VAR__);
    
    local_scalar_t__ tacc;
    tacc = DUMMY_VAR__;
    
    current_statement__ = 171;
    tacc = x_r[(1 - 1)];
    current_statement__ = 172;
    validate_non_negative_index("tp_rmNA", "lentp_rmNA", lentp_rmNA);
    Eigen::Matrix<local_scalar_t__, -1, 1> tp_rmNA;
    tp_rmNA = Eigen::Matrix<local_scalar_t__, -1, 1>(lentp_rmNA);
    stan::math::fill(tp_rmNA, DUMMY_VAR__);
    
    current_statement__ = 173;
    assign(tp_rmNA, nil_index_list(),
      to_vector(
        rvalue(x_r,
          cons_list(index_min_max(2, (lentp_rmNA + 1)), nil_index_list()),
          "x_r")), "assigning variable tp_rmNA");
    current_statement__ = 174;
    validate_non_negative_index("Cexp_rmNA", "lentp_rmNA", lentp_rmNA);
    Eigen::Matrix<local_scalar_t__, -1, 1> Cexp_rmNA;
    Cexp_rmNA = Eigen::Matrix<local_scalar_t__, -1, 1>(lentp_rmNA);
    stan::math::fill(Cexp_rmNA, DUMMY_VAR__);
    
    current_statement__ = 175;
    assign(Cexp_rmNA, nil_index_list(),
      to_vector(
        rvalue(x_r,
          cons_list(
            index_min_max((lentp_rmNA + 2), ((lentp_rmNA + 1) + lentp_rmNA)),
            nil_index_list()), "x_r")), "assigning variable Cexp_rmNA");
    local_scalar_t__ U;
    U = DUMMY_VAR__;
    
    local_scalar_t__ M;
    M = DUMMY_VAR__;
    
    local_scalar_t__ E;
    E = DUMMY_VAR__;
    
    current_statement__ = 183;
    if (logical_eq(n_met, 0)) {
      current_statement__ = 181;
      M = 0;
    } else {
      current_statement__ = 179;
      M = sum(km);
    }
    current_statement__ = 184;
    E = sum(ke);
    current_statement__ = 185;
    U = (ku[(1 - 1)] * interpolate(t, tp_rmNA, Cexp_rmNA, pstream__));
    current_statement__ = 190;
    if (logical_lte(t, tacc)) {
      current_statement__ = 188;
      assign(dydt, cons_list(index_uni(1), nil_index_list()),
        (U - ((E + M) * y[(1 - 1)])), "assigning variable dydt");
    } else {
      current_statement__ = 186;
      assign(dydt, cons_list(index_uni(1), nil_index_list()),
        (-(E + M) * y[(1 - 1)]), "assigning variable dydt");
    }
    current_statement__ = 195;
    if (logical_gt(n_met, 0)) {
      current_statement__ = 193;
      for (int i = 2; i <= (n_met + 1); ++i) {
        current_statement__ = 191;
        assign(dydt, cons_list(index_uni(i), nil_index_list()),
          ((km[(i - 1)] * y[(1 - 1)]) - (kem[(i - 1)] * y[(i - 1)])),
          "assigning variable dydt");}
    } 
    current_statement__ = 196;
    return dydt;
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
  }
  
}
struct odeTK_functor__ {
template <typename T0__, typename T1__, typename T2__, typename T3__>
std::vector<stan::promote_args_t<T0__, T1__, T2__,
T3__>>
operator()(const T0__& t, const std::vector<T1__>& y,
           const std::vector<T2__>& theta, const std::vector<T3__>& x_r,
           const std::vector<int>& x_i, std::ostream* pstream__)  const 
{
return odeTK(t, y, theta, x_r, x_i, pstream__);
}
};
#include <stan_meta_header.hpp>
class model_TK_predict final : public model_base_crtp<model_TK_predict> {
private:
  int lentp;
  Eigen::Matrix<double, -1, 1> tp;
  int len_vt;
  Eigen::Matrix<double, -1, 1> vt;
  int n_exp;
  Eigen::Matrix<double, -1, -1> Cexp;
  int rankacc;
  double tacc;
  double C0;
  double elim_rate;
  int n_out;
  int n_met;
  int N_samples;
  Eigen::Matrix<double, -1, -1> log10ku;
  Eigen::Matrix<double, -1, -1> log10ke;
  Eigen::Matrix<double, -1, -1> log10km;
  Eigen::Matrix<double, -1, -1> log10kem;
  std::vector<double> M;
  std::vector<double> E;
  std::vector<std::vector<double>> sigmaCGpred;
  Eigen::Matrix<double, -1, -1> sigmaCmetpred;
  std::vector<std::vector<double>> gmax;
  std::vector<std::vector<double>> G0;
 
public:
  ~model_TK_predict() { }
  
  inline std::string model_name() const final { return "model_TK_predict"; }
  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.26.1-4-gd72b68b7-dirty", "stancflags = "};
  }
  
  
  model_TK_predict(stan::io::var_context& context__,
                   unsigned int random_seed__ = 0,
                   std::ostream* pstream__ = nullptr) : model_base_crtp(0) {
    using local_scalar_t__ = double ;
    boost::ecuyer1988 base_rng__ = 
        stan::services::util::create_rng(random_seed__, 0);
    (void) base_rng__;  // suppress unused var warning
    static const char* function__ = "model_TK_predict_namespace::model_TK_predict";
    (void) function__;  // suppress unused var warning
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    
    try {
      int pos__;
      pos__ = std::numeric_limits<int>::min();
      
      pos__ = 1;
      current_statement__ = 73;
      context__.validate_dims("data initialization","lentp","int",
          context__.to_vec());
      lentp = std::numeric_limits<int>::min();
      
      current_statement__ = 73;
      lentp = context__.vals_i("lentp")[(1 - 1)];
      current_statement__ = 73;
      current_statement__ = 73;
      check_greater_or_equal(function__, "lentp", lentp, 0);
      current_statement__ = 74;
      validate_non_negative_index("tp", "lentp", lentp);
      current_statement__ = 75;
      context__.validate_dims("data initialization","tp","double",
          context__.to_vec(lentp));
      tp = Eigen::Matrix<double, -1, 1>(lentp);
      stan::math::fill(tp, std::numeric_limits<double>::quiet_NaN());
      
      {
        std::vector<local_scalar_t__> tp_flat__;
        current_statement__ = 75;
        assign(tp_flat__, nil_index_list(), context__.vals_r("tp"),
          "assigning variable tp_flat__");
        current_statement__ = 75;
        pos__ = 1;
        current_statement__ = 75;
        for (int sym1__ = 1; sym1__ <= lentp; ++sym1__) {
          current_statement__ = 75;
          assign(tp, cons_list(index_uni(sym1__), nil_index_list()),
            tp_flat__[(pos__ - 1)], "assigning variable tp");
          current_statement__ = 75;
          pos__ = (pos__ + 1);}
      }
      current_statement__ = 76;
      context__.validate_dims("data initialization","len_vt","int",
          context__.to_vec());
      len_vt = std::numeric_limits<int>::min();
      
      current_statement__ = 76;
      len_vt = context__.vals_i("len_vt")[(1 - 1)];
      current_statement__ = 76;
      current_statement__ = 76;
      check_greater_or_equal(function__, "len_vt", len_vt, 0);
      current_statement__ = 77;
      validate_non_negative_index("vt", "len_vt", len_vt);
      current_statement__ = 78;
      context__.validate_dims("data initialization","vt","double",
          context__.to_vec(len_vt));
      vt = Eigen::Matrix<double, -1, 1>(len_vt);
      stan::math::fill(vt, std::numeric_limits<double>::quiet_NaN());
      
      {
        std::vector<local_scalar_t__> vt_flat__;
        current_statement__ = 78;
        assign(vt_flat__, nil_index_list(), context__.vals_r("vt"),
          "assigning variable vt_flat__");
        current_statement__ = 78;
        pos__ = 1;
        current_statement__ = 78;
        for (int sym1__ = 1; sym1__ <= len_vt; ++sym1__) {
          current_statement__ = 78;
          assign(vt, cons_list(index_uni(sym1__), nil_index_list()),
            vt_flat__[(pos__ - 1)], "assigning variable vt");
          current_statement__ = 78;
          pos__ = (pos__ + 1);}
      }
      current_statement__ = 79;
      context__.validate_dims("data initialization","n_exp","int",
          context__.to_vec());
      n_exp = std::numeric_limits<int>::min();
      
      current_statement__ = 79;
      n_exp = context__.vals_i("n_exp")[(1 - 1)];
      current_statement__ = 79;
      current_statement__ = 79;
      check_greater_or_equal(function__, "n_exp", n_exp, 0);
      current_statement__ = 80;
      validate_non_negative_index("Cexp", "len_vt", len_vt);
      current_statement__ = 81;
      validate_non_negative_index("Cexp", "n_exp", n_exp);
      current_statement__ = 82;
      context__.validate_dims("data initialization","Cexp","double",
          context__.to_vec(len_vt, n_exp));
      Cexp = Eigen::Matrix<double, -1, -1>(len_vt, n_exp);
      stan::math::fill(Cexp, std::numeric_limits<double>::quiet_NaN());
      
      {
        std::vector<local_scalar_t__> Cexp_flat__;
        current_statement__ = 82;
        assign(Cexp_flat__, nil_index_list(), context__.vals_r("Cexp"),
          "assigning variable Cexp_flat__");
        current_statement__ = 82;
        pos__ = 1;
        current_statement__ = 82;
        for (int sym1__ = 1; sym1__ <= n_exp; ++sym1__) {
          current_statement__ = 82;
          for (int sym2__ = 1; sym2__ <= len_vt; ++sym2__) {
            current_statement__ = 82;
            assign(Cexp,
              cons_list(index_uni(sym2__),
                cons_list(index_uni(sym1__), nil_index_list())),
              Cexp_flat__[(pos__ - 1)], "assigning variable Cexp");
            current_statement__ = 82;
            pos__ = (pos__ + 1);}}
      }
      current_statement__ = 83;
      context__.validate_dims("data initialization","rankacc","int",
          context__.to_vec());
      rankacc = std::numeric_limits<int>::min();
      
      current_statement__ = 83;
      rankacc = context__.vals_i("rankacc")[(1 - 1)];
      current_statement__ = 83;
      current_statement__ = 83;
      check_greater_or_equal(function__, "rankacc", rankacc, 0);
      current_statement__ = 84;
      context__.validate_dims("data initialization","tacc","double",
          context__.to_vec());
      tacc = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 84;
      tacc = context__.vals_r("tacc")[(1 - 1)];
      current_statement__ = 84;
      current_statement__ = 84;
      check_greater_or_equal(function__, "tacc", tacc, 0);
      current_statement__ = 85;
      context__.validate_dims("data initialization","C0","double",
          context__.to_vec());
      C0 = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 85;
      C0 = context__.vals_r("C0")[(1 - 1)];
      current_statement__ = 85;
      current_statement__ = 85;
      check_greater_or_equal(function__, "C0", C0, 0);
      current_statement__ = 86;
      context__.validate_dims("data initialization","elim_rate","double",
          context__.to_vec());
      elim_rate = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 86;
      elim_rate = context__.vals_r("elim_rate")[(1 - 1)];
      current_statement__ = 87;
      context__.validate_dims("data initialization","n_out","int",
          context__.to_vec());
      n_out = std::numeric_limits<int>::min();
      
      current_statement__ = 87;
      n_out = context__.vals_i("n_out")[(1 - 1)];
      current_statement__ = 87;
      current_statement__ = 87;
      check_greater_or_equal(function__, "n_out", n_out, 0);
      current_statement__ = 88;
      context__.validate_dims("data initialization","n_met","int",
          context__.to_vec());
      n_met = std::numeric_limits<int>::min();
      
      current_statement__ = 88;
      n_met = context__.vals_i("n_met")[(1 - 1)];
      current_statement__ = 88;
      current_statement__ = 88;
      check_greater_or_equal(function__, "n_met", n_met, 0);
      current_statement__ = 89;
      context__.validate_dims("data initialization","N_samples","int",
          context__.to_vec());
      N_samples = std::numeric_limits<int>::min();
      
      current_statement__ = 89;
      N_samples = context__.vals_i("N_samples")[(1 - 1)];
      current_statement__ = 90;
      validate_non_negative_index("log10ku", "N_samples", N_samples);
      current_statement__ = 91;
      validate_non_negative_index("log10ku", "n_exp", n_exp);
      current_statement__ = 92;
      context__.validate_dims("data initialization","log10ku","double",
          context__.to_vec(N_samples, n_exp));
      log10ku = Eigen::Matrix<double, -1, -1>(N_samples, n_exp);
      stan::math::fill(log10ku, std::numeric_limits<double>::quiet_NaN());
      
      {
        std::vector<local_scalar_t__> log10ku_flat__;
        current_statement__ = 92;
        assign(log10ku_flat__, nil_index_list(), context__.vals_r("log10ku"),
          "assigning variable log10ku_flat__");
        current_statement__ = 92;
        pos__ = 1;
        current_statement__ = 92;
        for (int sym1__ = 1; sym1__ <= n_exp; ++sym1__) {
          current_statement__ = 92;
          for (int sym2__ = 1; sym2__ <= N_samples; ++sym2__) {
            current_statement__ = 92;
            assign(log10ku,
              cons_list(index_uni(sym2__),
                cons_list(index_uni(sym1__), nil_index_list())),
              log10ku_flat__[(pos__ - 1)], "assigning variable log10ku");
            current_statement__ = 92;
            pos__ = (pos__ + 1);}}
      }
      current_statement__ = 93;
      validate_non_negative_index("log10ke", "N_samples", N_samples);
      current_statement__ = 94;
      validate_non_negative_index("log10ke", "n_out", n_out);
      current_statement__ = 95;
      context__.validate_dims("data initialization","log10ke","double",
          context__.to_vec(N_samples, n_out));
      log10ke = Eigen::Matrix<double, -1, -1>(N_samples, n_out);
      stan::math::fill(log10ke, std::numeric_limits<double>::quiet_NaN());
      
      {
        std::vector<local_scalar_t__> log10ke_flat__;
        current_statement__ = 95;
        assign(log10ke_flat__, nil_index_list(), context__.vals_r("log10ke"),
          "assigning variable log10ke_flat__");
        current_statement__ = 95;
        pos__ = 1;
        current_statement__ = 95;
        for (int sym1__ = 1; sym1__ <= n_out; ++sym1__) {
          current_statement__ = 95;
          for (int sym2__ = 1; sym2__ <= N_samples; ++sym2__) {
            current_statement__ = 95;
            assign(log10ke,
              cons_list(index_uni(sym2__),
                cons_list(index_uni(sym1__), nil_index_list())),
              log10ke_flat__[(pos__ - 1)], "assigning variable log10ke");
            current_statement__ = 95;
            pos__ = (pos__ + 1);}}
      }
      current_statement__ = 96;
      validate_non_negative_index("log10km", "N_samples", N_samples);
      current_statement__ = 97;
      validate_non_negative_index("log10km", "n_met", n_met);
      current_statement__ = 98;
      context__.validate_dims("data initialization","log10km","double",
          context__.to_vec(N_samples, n_met));
      log10km = Eigen::Matrix<double, -1, -1>(N_samples, n_met);
      stan::math::fill(log10km, std::numeric_limits<double>::quiet_NaN());
      
      {
        std::vector<local_scalar_t__> log10km_flat__;
        current_statement__ = 98;
        assign(log10km_flat__, nil_index_list(), context__.vals_r("log10km"),
          "assigning variable log10km_flat__");
        current_statement__ = 98;
        pos__ = 1;
        current_statement__ = 98;
        for (int sym1__ = 1; sym1__ <= n_met; ++sym1__) {
          current_statement__ = 98;
          for (int sym2__ = 1; sym2__ <= N_samples; ++sym2__) {
            current_statement__ = 98;
            assign(log10km,
              cons_list(index_uni(sym2__),
                cons_list(index_uni(sym1__), nil_index_list())),
              log10km_flat__[(pos__ - 1)], "assigning variable log10km");
            current_statement__ = 98;
            pos__ = (pos__ + 1);}}
      }
      current_statement__ = 99;
      validate_non_negative_index("log10kem", "N_samples", N_samples);
      current_statement__ = 100;
      validate_non_negative_index("log10kem", "n_met", n_met);
      current_statement__ = 101;
      context__.validate_dims("data initialization","log10kem","double",
          context__.to_vec(N_samples, n_met));
      log10kem = Eigen::Matrix<double, -1, -1>(N_samples, n_met);
      stan::math::fill(log10kem, std::numeric_limits<double>::quiet_NaN());
      
      {
        std::vector<local_scalar_t__> log10kem_flat__;
        current_statement__ = 101;
        assign(log10kem_flat__, nil_index_list(),
          context__.vals_r("log10kem"), "assigning variable log10kem_flat__");
        current_statement__ = 101;
        pos__ = 1;
        current_statement__ = 101;
        for (int sym1__ = 1; sym1__ <= n_met; ++sym1__) {
          current_statement__ = 101;
          for (int sym2__ = 1; sym2__ <= N_samples; ++sym2__) {
            current_statement__ = 101;
            assign(log10kem,
              cons_list(index_uni(sym2__),
                cons_list(index_uni(sym1__), nil_index_list())),
              log10kem_flat__[(pos__ - 1)], "assigning variable log10kem");
            current_statement__ = 101;
            pos__ = (pos__ + 1);}}
      }
      current_statement__ = 102;
      validate_non_negative_index("M", "N_samples", N_samples);
      current_statement__ = 103;
      context__.validate_dims("data initialization","M","double",
          context__.to_vec(N_samples));
      M = std::vector<double>(N_samples, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 103;
      assign(M, nil_index_list(), context__.vals_r("M"),
        "assigning variable M");
      current_statement__ = 104;
      validate_non_negative_index("E", "N_samples", N_samples);
      current_statement__ = 105;
      context__.validate_dims("data initialization","E","double",
          context__.to_vec(N_samples));
      E = std::vector<double>(N_samples, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 105;
      assign(E, nil_index_list(), context__.vals_r("E"),
        "assigning variable E");
      current_statement__ = 106;
      validate_non_negative_index("sigmaCGpred", "N_samples", N_samples);
      current_statement__ = 107;
      validate_non_negative_index("sigmaCGpred", "n_out", n_out);
      current_statement__ = 108;
      context__.validate_dims("data initialization","sigmaCGpred","double",
          context__.to_vec(N_samples, n_out));
      sigmaCGpred = std::vector<std::vector<double>>(N_samples, std::vector<double>(n_out, std::numeric_limits<double>::quiet_NaN()));
      
      {
        std::vector<local_scalar_t__> sigmaCGpred_flat__;
        current_statement__ = 108;
        assign(sigmaCGpred_flat__, nil_index_list(),
          context__.vals_r("sigmaCGpred"),
          "assigning variable sigmaCGpred_flat__");
        current_statement__ = 108;
        pos__ = 1;
        current_statement__ = 108;
        for (int sym1__ = 1; sym1__ <= n_out; ++sym1__) {
          current_statement__ = 108;
          for (int sym2__ = 1; sym2__ <= N_samples; ++sym2__) {
            current_statement__ = 108;
            assign(sigmaCGpred,
              cons_list(index_uni(sym2__),
                cons_list(index_uni(sym1__), nil_index_list())),
              sigmaCGpred_flat__[(pos__ - 1)],
              "assigning variable sigmaCGpred");
            current_statement__ = 108;
            pos__ = (pos__ + 1);}}
      }
      current_statement__ = 108;
      for (int sym1__ = 1; sym1__ <= N_samples; ++sym1__) {
        current_statement__ = 108;
        for (int sym2__ = 1; sym2__ <= n_out; ++sym2__) {
          current_statement__ = 108;
          current_statement__ = 108;
          check_greater_or_equal(function__, "sigmaCGpred[sym1__, sym2__]",
                                 sigmaCGpred[(sym1__ - 1)][(sym2__ - 1)], 0);
        }}
      current_statement__ = 109;
      validate_non_negative_index("sigmaCmetpred", "N_samples", N_samples);
      current_statement__ = 110;
      validate_non_negative_index("sigmaCmetpred", "n_met", n_met);
      current_statement__ = 111;
      context__.validate_dims("data initialization","sigmaCmetpred","double",
          context__.to_vec(N_samples, n_met));
      sigmaCmetpred = Eigen::Matrix<double, -1, -1>(N_samples, n_met);
      stan::math::fill(sigmaCmetpred, std::numeric_limits<double>::quiet_NaN());
      
      {
        std::vector<local_scalar_t__> sigmaCmetpred_flat__;
        current_statement__ = 111;
        assign(sigmaCmetpred_flat__, nil_index_list(),
          context__.vals_r("sigmaCmetpred"),
          "assigning variable sigmaCmetpred_flat__");
        current_statement__ = 111;
        pos__ = 1;
        current_statement__ = 111;
        for (int sym1__ = 1; sym1__ <= n_met; ++sym1__) {
          current_statement__ = 111;
          for (int sym2__ = 1; sym2__ <= N_samples; ++sym2__) {
            current_statement__ = 111;
            assign(sigmaCmetpred,
              cons_list(index_uni(sym2__),
                cons_list(index_uni(sym1__), nil_index_list())),
              sigmaCmetpred_flat__[(pos__ - 1)],
              "assigning variable sigmaCmetpred");
            current_statement__ = 111;
            pos__ = (pos__ + 1);}}
      }
      current_statement__ = 111;
      for (int sym1__ = 1; sym1__ <= N_samples; ++sym1__) {
        current_statement__ = 111;
        for (int sym2__ = 1; sym2__ <= n_met; ++sym2__) {
          current_statement__ = 111;
          current_statement__ = 111;
          check_greater_or_equal(function__, "sigmaCmetpred[sym1__, sym2__]",
                                 rvalue(sigmaCmetpred,
                                   cons_list(index_uni(sym1__),
                                     cons_list(index_uni(sym2__),
                                       nil_index_list())), "sigmaCmetpred"),
                                 0);}}
      current_statement__ = 112;
      validate_non_negative_index("gmax", "N_samples", N_samples);
      current_statement__ = 113;
      validate_non_negative_index("gmax", "n_out - 1", (n_out - 1));
      current_statement__ = 114;
      context__.validate_dims("data initialization","gmax","double",
          context__.to_vec(N_samples, (n_out - 1)));
      gmax = std::vector<std::vector<double>>(N_samples, std::vector<double>(
        (n_out - 1), std::numeric_limits<double>::quiet_NaN()));
      
      {
        std::vector<local_scalar_t__> gmax_flat__;
        current_statement__ = 114;
        assign(gmax_flat__, nil_index_list(), context__.vals_r("gmax"),
          "assigning variable gmax_flat__");
        current_statement__ = 114;
        pos__ = 1;
        current_statement__ = 114;
        for (int sym1__ = 1; sym1__ <= (n_out - 1); ++sym1__) {
          current_statement__ = 114;
          for (int sym2__ = 1; sym2__ <= N_samples; ++sym2__) {
            current_statement__ = 114;
            assign(gmax,
              cons_list(index_uni(sym2__),
                cons_list(index_uni(sym1__), nil_index_list())),
              gmax_flat__[(pos__ - 1)], "assigning variable gmax");
            current_statement__ = 114;
            pos__ = (pos__ + 1);}}
      }
      current_statement__ = 114;
      for (int sym1__ = 1; sym1__ <= N_samples; ++sym1__) {
        current_statement__ = 114;
        for (int sym2__ = 1; sym2__ <= (n_out - 1); ++sym2__) {
          current_statement__ = 114;
          current_statement__ = 114;
          check_greater_or_equal(function__, "gmax[sym1__, sym2__]",
                                 gmax[(sym1__ - 1)][(sym2__ - 1)], 0);}}
      current_statement__ = 115;
      validate_non_negative_index("G0", "N_samples", N_samples);
      current_statement__ = 116;
      validate_non_negative_index("G0", "n_out - 1", (n_out - 1));
      current_statement__ = 117;
      context__.validate_dims("data initialization","G0","double",
          context__.to_vec(N_samples, (n_out - 1)));
      G0 = std::vector<std::vector<double>>(N_samples, std::vector<double>(
        (n_out - 1), std::numeric_limits<double>::quiet_NaN()));
      
      {
        std::vector<local_scalar_t__> G0_flat__;
        current_statement__ = 117;
        assign(G0_flat__, nil_index_list(), context__.vals_r("G0"),
          "assigning variable G0_flat__");
        current_statement__ = 117;
        pos__ = 1;
        current_statement__ = 117;
        for (int sym1__ = 1; sym1__ <= (n_out - 1); ++sym1__) {
          current_statement__ = 117;
          for (int sym2__ = 1; sym2__ <= N_samples; ++sym2__) {
            current_statement__ = 117;
            assign(G0,
              cons_list(index_uni(sym2__),
                cons_list(index_uni(sym1__), nil_index_list())),
              G0_flat__[(pos__ - 1)], "assigning variable G0");
            current_statement__ = 117;
            pos__ = (pos__ + 1);}}
      }
      current_statement__ = 117;
      for (int sym1__ = 1; sym1__ <= N_samples; ++sym1__) {
        current_statement__ = 117;
        for (int sym2__ = 1; sym2__ <= (n_out - 1); ++sym2__) {
          current_statement__ = 117;
          current_statement__ = 117;
          check_greater_or_equal(function__, "G0[sym1__, sym2__]",
                                 G0[(sym1__ - 1)][(sym2__ - 1)], 0);}}
      current_statement__ = 118;
      validate_non_negative_index("CGobs_out", "lentp", lentp);
      current_statement__ = 119;
      validate_non_negative_index("CGobs_out", "n_out", n_out);
      current_statement__ = 120;
      validate_non_negative_index("Cmet_out", "lentp", lentp);
      current_statement__ = 121;
      validate_non_negative_index("Cmet_out", "n_met", n_met);
      current_statement__ = 122;
      validate_non_negative_index("Cexp_interpol", "lentp", lentp);
      current_statement__ = 123;
      validate_non_negative_index("Cexp_interpol", "n_exp", n_exp);
      current_statement__ = 124;
      validate_non_negative_index("ku", "n_exp", n_exp);
      current_statement__ = 125;
      validate_non_negative_index("ke", "n_out", n_out);
      current_statement__ = 126;
      validate_non_negative_index("km", "n_met", n_met);
      current_statement__ = 127;
      validate_non_negative_index("kem", "n_met", n_met);
      current_statement__ = 128;
      validate_non_negative_index("U", "lentp", lentp);
      current_statement__ = 129;
      validate_non_negative_index("R", "lentp", lentp);
      current_statement__ = 130;
      validate_non_negative_index("D", "n_met", n_met);
      current_statement__ = 131;
      validate_non_negative_index("CGpred", "lentp", lentp);
      current_statement__ = 132;
      validate_non_negative_index("CGpred", "n_out", n_out);
      current_statement__ = 133;
      validate_non_negative_index("Cmetpred", "lentp", lentp);
      current_statement__ = 134;
      validate_non_negative_index("Cmetpred", "n_met", n_met);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    num_params_r__ = 0U;
    
    try {
      
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
  }
  template <bool propto__, bool jacobian__, typename VecR, typename VecI, stan::require_vector_like_t<VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline stan::scalar_type_t<VecR> log_prob_impl(VecR& params_r__,
                                                 VecI& params_i__,
                                                 std::ostream* pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    static const char* function__ = "model_TK_predict_namespace::log_prob";
(void) function__;  // suppress unused var warning
    stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    
    try {
      
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
    } // log_prob_impl() 
    
  template <typename RNG, typename VecR, typename VecI, typename VecVar, stan::require_vector_like_vt<std::is_floating_point, VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr, stan::require_std_vector_vt<std::is_floating_point, VecVar>* = nullptr>
  inline void write_array_impl(RNG& base_rng__, VecR& params_r__,
                               VecI& params_i__, VecVar& vars__,
                               const bool emit_transformed_parameters__ = true,
                               const bool emit_generated_quantities__ = true,
                               std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    vars__.resize(0);
    stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
    static const char* function__ = "model_TK_predict_namespace::write_array";
(void) function__;  // suppress unused var warning
    (void) function__;  // suppress unused var warning
    double lp__ = 0.0;
    (void) lp__;  // dummy to suppress unused var warning
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    
    try {
      if (logical_negation((primitive_value(emit_transformed_parameters__) ||
            primitive_value(emit_generated_quantities__)))) {
        return ;
      } 
      if (logical_negation(emit_generated_quantities__)) {
        return ;
      } 
      std::vector<std::vector<double>> CGobs_out;
      CGobs_out = std::vector<std::vector<double>>(lentp, std::vector<double>(n_out, std::numeric_limits<double>::quiet_NaN()));
      
      std::vector<std::vector<double>> Cmet_out;
      Cmet_out = std::vector<std::vector<double>>(lentp, std::vector<double>(n_met, std::numeric_limits<double>::quiet_NaN()));
      
      Eigen::Matrix<double, -1, -1> Cexp_interpol;
      Cexp_interpol = Eigen::Matrix<double, -1, -1>(lentp, n_exp);
      stan::math::fill(Cexp_interpol, std::numeric_limits<double>::quiet_NaN());
      
      Eigen::Matrix<double, -1, 1> ku;
      ku = Eigen::Matrix<double, -1, 1>(n_exp);
      stan::math::fill(ku, std::numeric_limits<double>::quiet_NaN());
      
      Eigen::Matrix<double, -1, 1> ke;
      ke = Eigen::Matrix<double, -1, 1>(n_out);
      stan::math::fill(ke, std::numeric_limits<double>::quiet_NaN());
      
      Eigen::Matrix<double, -1, 1> km;
      km = Eigen::Matrix<double, -1, 1>(n_met);
      stan::math::fill(km, std::numeric_limits<double>::quiet_NaN());
      
      Eigen::Matrix<double, -1, 1> kem;
      kem = Eigen::Matrix<double, -1, 1>(n_met);
      stan::math::fill(kem, std::numeric_limits<double>::quiet_NaN());
      
      Eigen::Matrix<double, -1, 1> U;
      U = Eigen::Matrix<double, -1, 1>(lentp);
      stan::math::fill(U, std::numeric_limits<double>::quiet_NaN());
      
      Eigen::Matrix<double, -1, 1> R;
      R = Eigen::Matrix<double, -1, 1>(lentp);
      stan::math::fill(R, std::numeric_limits<double>::quiet_NaN());
      
      Eigen::Matrix<double, -1, 1> D;
      D = Eigen::Matrix<double, -1, 1>(n_met);
      stan::math::fill(D, std::numeric_limits<double>::quiet_NaN());
      
      Eigen::Matrix<double, -1, -1> CGpred;
      CGpred = Eigen::Matrix<double, -1, -1>(lentp, n_out);
      stan::math::fill(CGpred, std::numeric_limits<double>::quiet_NaN());
      
      Eigen::Matrix<double, -1, -1> Cmetpred;
      Cmetpred = Eigen::Matrix<double, -1, -1>(lentp, n_met);
      stan::math::fill(Cmetpred, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 17;
      for (int i = 1; i <= n_exp; ++i) {
        current_statement__ = 15;
        for (int t = 1; t <= lentp; ++t) {
          current_statement__ = 13;
          assign(Cexp_interpol,
            cons_list(index_uni(t),
              cons_list(index_uni(i), nil_index_list())),
            interpolate(tp[(t - 1)], vt,
              rvalue(Cexp,
                cons_list(index_min_max(1, len_vt),
                  cons_list(index_uni(i), nil_index_list())), "Cexp"), pstream__),
            "assigning variable Cexp_interpol");}}
      current_statement__ = 72;
      for (int s = 1; s <= N_samples; ++s) {
        current_statement__ = 20;
        for (int i = 1; i <= n_exp; ++i) {
          current_statement__ = 18;
          assign(ku, cons_list(index_uni(i), nil_index_list()),
            pow(10,
              rvalue(log10ku,
                cons_list(index_uni(s),
                  cons_list(index_uni(i), nil_index_list())), "log10ku")),
            "assigning variable ku");}
        current_statement__ = 27;
        for (int i = 1; i <= n_out; ++i) {
          current_statement__ = 25;
          if (logical_negation(is_inf(elim_rate))) {
            current_statement__ = 23;
            assign(ke, cons_list(index_uni(i), nil_index_list()), 0,
              "assigning variable ke");
          } else {
            current_statement__ = 21;
            assign(ke, cons_list(index_uni(i), nil_index_list()),
              pow(10,
                rvalue(log10ke,
                  cons_list(index_uni(s),
                    cons_list(index_uni(i), nil_index_list())), "log10ke")),
              "assigning variable ke");
          }}
        current_statement__ = 31;
        for (int i = 1; i <= n_met; ++i) {
          current_statement__ = 28;
          assign(km, cons_list(index_uni(i), nil_index_list()),
            pow(10,
              rvalue(log10km,
                cons_list(index_uni(s),
                  cons_list(index_uni(i), nil_index_list())), "log10km")),
            "assigning variable km");
          current_statement__ = 29;
          assign(kem, cons_list(index_uni(i), nil_index_list()),
            pow(10,
              rvalue(log10kem,
                cons_list(index_uni(s),
                  cons_list(index_uni(i), nil_index_list())), "log10kem")),
            "assigning variable kem");}
        current_statement__ = 35;
        for (int t = 1; t <= lentp; ++t) {
          current_statement__ = 32;
          assign(U, cons_list(index_uni(t), nil_index_list()),
            multiply(
              rvalue(Cexp_interpol,
                cons_list(index_uni(t),
                  cons_list(index_min_max(1, n_exp), nil_index_list())),
                "Cexp_interpol"), ku), "assigning variable U");
          current_statement__ = 33;
          assign(R, cons_list(index_uni(t), nil_index_list()),
            (U[(t - 1)] / (E[(s - 1)] + M[(s - 1)])), "assigning variable R");
        }
        current_statement__ = 38;
        for (int i = 1; i <= n_met; ++i) {
          current_statement__ = 36;
          assign(D, cons_list(index_uni(i), nil_index_list()),
            (kem[(i - 1)] - (E[(s - 1)] + M[(s - 1)])),
            "assigning variable D");}
        current_statement__ = 46;
        for (int t = 1; t <= rankacc; ++t) {
          current_statement__ = 39;
          assign(CGpred,
            cons_list(index_uni(t),
              cons_list(index_uni(1), nil_index_list())),
            (((C0 - R[(t - 1)]) *
               stan::math::exp((-(E[(s - 1)] + M[(s - 1)]) * tp[(t - 1)]))) +
              R[(t - 1)]), "assigning variable CGpred");
          current_statement__ = 44;
          if (logical_gt(n_met, 0)) {
            current_statement__ = 42;
            for (int i = 1; i <= n_met; ++i) {
              current_statement__ = 40;
              assign(Cmetpred,
                cons_list(index_uni(t),
                  cons_list(index_uni(i), nil_index_list())),
                (km[(i - 1)] *
                  ((((C0 - R[(t - 1)]) / D[(i - 1)]) *
                     (stan::math::exp(
                        (-(E[(s - 1)] + M[(s - 1)]) * tp[(t - 1)])) -
                       stan::math::exp((-kem[(i - 1)] * tp[(t - 1)])))) +
                    ((R[(t - 1)] / kem[(i - 1)]) *
                      (1 - stan::math::exp(-(kem[(i - 1)] * tp[(t - 1)])))))),
                "assigning variable Cmetpred");}
          } }
        current_statement__ = 54;
        for (int t = (rankacc + 1); t <= lentp; ++t) {
          current_statement__ = 47;
          assign(CGpred,
            cons_list(index_uni(t),
              cons_list(index_uni(1), nil_index_list())),
            ((C0 -
               (R[(t - 1)] *
                 (1 - stan::math::exp(((E[(s - 1)] + M[(s - 1)]) * tacc)))))
              * stan::math::exp((-(E[(s - 1)] + M[(s - 1)]) * tp[(t - 1)]))),
            "assigning variable CGpred");
          current_statement__ = 52;
          if (logical_gt(n_met, 0)) {
            current_statement__ = 50;
            for (int i = 1; i <= n_met; ++i) {
              current_statement__ = 48;
              assign(Cmetpred,
                cons_list(index_uni(t),
                  cons_list(index_uni(i), nil_index_list())),
                (km[(i - 1)] *
                  (((((C0 - R[(t - 1)]) / D[(i - 1)]) *
                      (stan::math::exp(
                         (-(E[(s - 1)] + M[(s - 1)]) * tp[(t - 1)])) -
                        stan::math::exp((-kem[(i - 1)] * tp[(t - 1)])))) +
                     ((R[(t - 1)] / kem[(i - 1)]) *
                       (stan::math::exp(
                          (-kem[(i - 1)] * (tp[(t - 1)] - tacc))) -
                         stan::math::exp((-kem[(i - 1)] * tp[(t - 1)]))))) +
                    ((R[(t - 1)] / D[(i - 1)]) *
                      (stan::math::exp(
                         (-(E[(s - 1)] + M[(s - 1)]) * (tp[(t - 1)] - tacc)))
                        -
                        stan::math::exp(
                          (-kem[(i - 1)] * (tp[(t - 1)] - tacc))))))),
                "assigning variable Cmetpred");}
          } }
        current_statement__ = 59;
        if (logical_eq(n_out, 2)) {
          current_statement__ = 57;
          for (int t = 1; t <= lentp; ++t) {
            current_statement__ = 55;
            assign(CGpred,
              cons_list(index_uni(t),
                cons_list(index_uni(2), nil_index_list())),
              (((G0[(s - 1)][(1 - 1)] - gmax[(s - 1)][(1 - 1)]) *
                 stan::math::exp((-ke[(2 - 1)] * tp[(t - 1)]))) +
                gmax[(s - 1)][(1 - 1)]), "assigning variable CGpred");}
        } 
        current_statement__ = 65;
        for (int t = 1; t <= lentp; ++t) {
          current_statement__ = 60;
          assign(CGobs_out,
            cons_list(index_uni(t),
              cons_list(index_uni(1), nil_index_list())),
            normal_rng(
              rvalue(CGpred,
                cons_list(index_uni(t),
                  cons_list(index_uni(1), nil_index_list())), "CGpred"),
              sigmaCGpred[(s - 1)][(1 - 1)], base_rng__),
            "assigning variable CGobs_out");
          current_statement__ = 63;
          for (int i = 1; i <= n_met; ++i) {
            current_statement__ = 61;
            assign(Cmet_out,
              cons_list(index_uni(t),
                cons_list(index_uni(i), nil_index_list())),
              normal_rng(
                rvalue(Cmetpred,
                  cons_list(index_uni(t),
                    cons_list(index_uni(i), nil_index_list())), "Cmetpred"),
                rvalue(sigmaCmetpred,
                  cons_list(index_uni(s),
                    cons_list(index_uni(i), nil_index_list())),
                  "sigmaCmetpred"), base_rng__),
              "assigning variable Cmet_out");}}
        current_statement__ = 70;
        if (logical_eq(n_out, 2)) {
          current_statement__ = 68;
          for (int t = 1; t <= lentp; ++t) {
            current_statement__ = 66;
            assign(CGobs_out,
              cons_list(index_uni(t),
                cons_list(index_uni(2), nil_index_list())),
              normal_rng(
                rvalue(CGpred,
                  cons_list(index_uni(t),
                    cons_list(index_uni(2), nil_index_list())), "CGpred"),
                sigmaCGpred[(s - 1)][(2 - 1)], base_rng__),
              "assigning variable CGobs_out");}
        } }
      current_statement__ = 4;
      for (int sym1__ = 1; sym1__ <= n_exp; ++sym1__) {
        current_statement__ = 4;
        current_statement__ = 4;
        check_greater_or_equal(function__, "ku[sym1__]", ku[(sym1__ - 1)], 0);
      }
      current_statement__ = 5;
      for (int sym1__ = 1; sym1__ <= n_out; ++sym1__) {
        current_statement__ = 5;
        current_statement__ = 5;
        check_greater_or_equal(function__, "ke[sym1__]", ke[(sym1__ - 1)], 0);
      }
      current_statement__ = 6;
      for (int sym1__ = 1; sym1__ <= n_met; ++sym1__) {
        current_statement__ = 6;
        current_statement__ = 6;
        check_greater_or_equal(function__, "km[sym1__]", km[(sym1__ - 1)], 0);
      }
      current_statement__ = 7;
      for (int sym1__ = 1; sym1__ <= n_met; ++sym1__) {
        current_statement__ = 7;
        current_statement__ = 7;
        check_greater_or_equal(function__, "kem[sym1__]", kem[(sym1__ - 1)],
                               0);}
      for (int sym1__ = 1; sym1__ <= n_out; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= lentp; ++sym2__) {
          vars__.emplace_back(CGobs_out[(sym2__ - 1)][(sym1__ - 1)]);}}
      for (int sym1__ = 1; sym1__ <= n_met; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= lentp; ++sym2__) {
          vars__.emplace_back(Cmet_out[(sym2__ - 1)][(sym1__ - 1)]);}}
      for (int sym1__ = 1; sym1__ <= n_exp; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= lentp; ++sym2__) {
          vars__.emplace_back(
            rvalue(Cexp_interpol,
              cons_list(index_uni(sym2__),
                cons_list(index_uni(sym1__), nil_index_list())),
              "Cexp_interpol"));}}
      for (int sym1__ = 1; sym1__ <= n_exp; ++sym1__) {
        vars__.emplace_back(ku[(sym1__ - 1)]);}
      for (int sym1__ = 1; sym1__ <= n_out; ++sym1__) {
        vars__.emplace_back(ke[(sym1__ - 1)]);}
      for (int sym1__ = 1; sym1__ <= n_met; ++sym1__) {
        vars__.emplace_back(km[(sym1__ - 1)]);}
      for (int sym1__ = 1; sym1__ <= n_met; ++sym1__) {
        vars__.emplace_back(kem[(sym1__ - 1)]);}
      for (int sym1__ = 1; sym1__ <= lentp; ++sym1__) {
        vars__.emplace_back(U[(sym1__ - 1)]);}
      for (int sym1__ = 1; sym1__ <= lentp; ++sym1__) {
        vars__.emplace_back(R[(sym1__ - 1)]);}
      for (int sym1__ = 1; sym1__ <= n_met; ++sym1__) {
        vars__.emplace_back(D[(sym1__ - 1)]);}
      for (int sym1__ = 1; sym1__ <= n_out; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= lentp; ++sym2__) {
          vars__.emplace_back(
            rvalue(CGpred,
              cons_list(index_uni(sym2__),
                cons_list(index_uni(sym1__), nil_index_list())), "CGpred"));}
      }
      for (int sym1__ = 1; sym1__ <= n_met; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= lentp; ++sym2__) {
          vars__.emplace_back(
            rvalue(Cmetpred,
              cons_list(index_uni(sym2__),
                cons_list(index_uni(sym1__), nil_index_list())), "Cmetpred"));
        }}
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    } // write_array_impl() 
    
  template <typename VecVar, typename VecI, stan::require_std_vector_t<VecVar>* = nullptr, stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline void transform_inits_impl(const stan::io::var_context& context__,
                                   VecI& params_i__, VecVar& vars__,
                                   std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    vars__.clear();
    vars__.reserve(num_params_r__);
    
    try {
      int pos__;
      pos__ = std::numeric_limits<int>::min();
      
      pos__ = 1;
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    } // transform_inits_impl() 
    
  inline void get_param_names(std::vector<std::string>& names__) const {
    
    names__.clear();
    names__.emplace_back("CGobs_out");
    names__.emplace_back("Cmet_out");
    names__.emplace_back("Cexp_interpol");
    names__.emplace_back("ku");
    names__.emplace_back("ke");
    names__.emplace_back("km");
    names__.emplace_back("kem");
    names__.emplace_back("U");
    names__.emplace_back("R");
    names__.emplace_back("D");
    names__.emplace_back("CGpred");
    names__.emplace_back("Cmetpred");
    } // get_param_names() 
    
  inline void get_dims(std::vector<std::vector<size_t>>& dimss__) const {
    dimss__.clear();
    dimss__.emplace_back(std::vector<size_t>{static_cast<size_t>(lentp),
                                             static_cast<size_t>(n_out)});
    
    dimss__.emplace_back(std::vector<size_t>{static_cast<size_t>(lentp),
                                             static_cast<size_t>(n_met)});
    
    dimss__.emplace_back(std::vector<size_t>{static_cast<size_t>(lentp),
                                             static_cast<size_t>(n_exp)});
    
    dimss__.emplace_back(std::vector<size_t>{static_cast<size_t>(n_exp)});
    
    dimss__.emplace_back(std::vector<size_t>{static_cast<size_t>(n_out)});
    
    dimss__.emplace_back(std::vector<size_t>{static_cast<size_t>(n_met)});
    
    dimss__.emplace_back(std::vector<size_t>{static_cast<size_t>(n_met)});
    
    dimss__.emplace_back(std::vector<size_t>{static_cast<size_t>(lentp)});
    
    dimss__.emplace_back(std::vector<size_t>{static_cast<size_t>(lentp)});
    
    dimss__.emplace_back(std::vector<size_t>{static_cast<size_t>(n_met)});
    
    dimss__.emplace_back(std::vector<size_t>{static_cast<size_t>(lentp),
                                             static_cast<size_t>(n_out)});
    
    dimss__.emplace_back(std::vector<size_t>{static_cast<size_t>(lentp),
                                             static_cast<size_t>(n_met)});
    
    } // get_dims() 
    
  inline void constrained_param_names(
                                      std::vector<std::string>& param_names__,
                                      bool emit_transformed_parameters__ = true,
                                      bool emit_generated_quantities__ = true) const
    final {
    
    
    if (emit_transformed_parameters__) {
      
    }
    
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= n_out; ++sym1__) {
        {
          for (int sym2__ = 1; sym2__ <= lentp; ++sym2__) {
            {
              param_names__.emplace_back(std::string() + "CGobs_out" + '.' + std::to_string(sym2__) + '.' + std::to_string(sym1__));
            }}
        }}
      for (int sym1__ = 1; sym1__ <= n_met; ++sym1__) {
        {
          for (int sym2__ = 1; sym2__ <= lentp; ++sym2__) {
            {
              param_names__.emplace_back(std::string() + "Cmet_out" + '.' + std::to_string(sym2__) + '.' + std::to_string(sym1__));
            }}
        }}
      for (int sym1__ = 1; sym1__ <= n_exp; ++sym1__) {
        {
          for (int sym2__ = 1; sym2__ <= lentp; ++sym2__) {
            {
              param_names__.emplace_back(std::string() + "Cexp_interpol" + '.' + std::to_string(sym2__) + '.' + std::to_string(sym1__));
            }}
        }}
      for (int sym1__ = 1; sym1__ <= n_exp; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "ku" + '.' + std::to_string(sym1__));
        }}
      for (int sym1__ = 1; sym1__ <= n_out; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "ke" + '.' + std::to_string(sym1__));
        }}
      for (int sym1__ = 1; sym1__ <= n_met; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "km" + '.' + std::to_string(sym1__));
        }}
      for (int sym1__ = 1; sym1__ <= n_met; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "kem" + '.' + std::to_string(sym1__));
        }}
      for (int sym1__ = 1; sym1__ <= lentp; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "U" + '.' + std::to_string(sym1__));
        }}
      for (int sym1__ = 1; sym1__ <= lentp; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "R" + '.' + std::to_string(sym1__));
        }}
      for (int sym1__ = 1; sym1__ <= n_met; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "D" + '.' + std::to_string(sym1__));
        }}
      for (int sym1__ = 1; sym1__ <= n_out; ++sym1__) {
        {
          for (int sym2__ = 1; sym2__ <= lentp; ++sym2__) {
            {
              param_names__.emplace_back(std::string() + "CGpred" + '.' + std::to_string(sym2__) + '.' + std::to_string(sym1__));
            }}
        }}
      for (int sym1__ = 1; sym1__ <= n_met; ++sym1__) {
        {
          for (int sym2__ = 1; sym2__ <= lentp; ++sym2__) {
            {
              param_names__.emplace_back(std::string() + "Cmetpred" + '.' + std::to_string(sym2__) + '.' + std::to_string(sym1__));
            }}
        }}
    }
    
    } // constrained_param_names() 
    
  inline void unconstrained_param_names(
                                        std::vector<std::string>& param_names__,
                                        bool emit_transformed_parameters__ = true,
                                        bool emit_generated_quantities__ = true) const
    final {
    
    
    if (emit_transformed_parameters__) {
      
    }
    
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= n_out; ++sym1__) {
        {
          for (int sym2__ = 1; sym2__ <= lentp; ++sym2__) {
            {
              param_names__.emplace_back(std::string() + "CGobs_out" + '.' + std::to_string(sym2__) + '.' + std::to_string(sym1__));
            }}
        }}
      for (int sym1__ = 1; sym1__ <= n_met; ++sym1__) {
        {
          for (int sym2__ = 1; sym2__ <= lentp; ++sym2__) {
            {
              param_names__.emplace_back(std::string() + "Cmet_out" + '.' + std::to_string(sym2__) + '.' + std::to_string(sym1__));
            }}
        }}
      for (int sym1__ = 1; sym1__ <= n_exp; ++sym1__) {
        {
          for (int sym2__ = 1; sym2__ <= lentp; ++sym2__) {
            {
              param_names__.emplace_back(std::string() + "Cexp_interpol" + '.' + std::to_string(sym2__) + '.' + std::to_string(sym1__));
            }}
        }}
      for (int sym1__ = 1; sym1__ <= n_exp; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "ku" + '.' + std::to_string(sym1__));
        }}
      for (int sym1__ = 1; sym1__ <= n_out; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "ke" + '.' + std::to_string(sym1__));
        }}
      for (int sym1__ = 1; sym1__ <= n_met; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "km" + '.' + std::to_string(sym1__));
        }}
      for (int sym1__ = 1; sym1__ <= n_met; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "kem" + '.' + std::to_string(sym1__));
        }}
      for (int sym1__ = 1; sym1__ <= lentp; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "U" + '.' + std::to_string(sym1__));
        }}
      for (int sym1__ = 1; sym1__ <= lentp; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "R" + '.' + std::to_string(sym1__));
        }}
      for (int sym1__ = 1; sym1__ <= n_met; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "D" + '.' + std::to_string(sym1__));
        }}
      for (int sym1__ = 1; sym1__ <= n_out; ++sym1__) {
        {
          for (int sym2__ = 1; sym2__ <= lentp; ++sym2__) {
            {
              param_names__.emplace_back(std::string() + "CGpred" + '.' + std::to_string(sym2__) + '.' + std::to_string(sym1__));
            }}
        }}
      for (int sym1__ = 1; sym1__ <= n_met; ++sym1__) {
        {
          for (int sym2__ = 1; sym2__ <= lentp; ++sym2__) {
            {
              param_names__.emplace_back(std::string() + "Cmetpred" + '.' + std::to_string(sym2__) + '.' + std::to_string(sym1__));
            }}
        }}
    }
    
    } // unconstrained_param_names() 
    
  inline std::string get_constrained_sizedtypes() const {
    stringstream s__;
    s__ << "[{\"name\":\"CGobs_out\",\"type\":{\"name\":\"array\",\"length\":" << lentp << ",\"element_type\":{\"name\":\"array\",\"length\":" << n_out << ",\"element_type\":{\"name\":\"real\"}}},\"block\":\"generated_quantities\"},{\"name\":\"Cmet_out\",\"type\":{\"name\":\"array\",\"length\":" << lentp << ",\"element_type\":{\"name\":\"array\",\"length\":" << n_met << ",\"element_type\":{\"name\":\"real\"}}},\"block\":\"generated_quantities\"},{\"name\":\"Cexp_interpol\",\"type\":{\"name\":\"matrix\",\"rows\":" << lentp << ",\"cols\":" << n_exp << "},\"block\":\"generated_quantities\"},{\"name\":\"ku\",\"type\":{\"name\":\"vector\",\"length\":" << n_exp << "},\"block\":\"generated_quantities\"},{\"name\":\"ke\",\"type\":{\"name\":\"vector\",\"length\":" << n_out << "},\"block\":\"generated_quantities\"},{\"name\":\"km\",\"type\":{\"name\":\"vector\",\"length\":" << n_met << "},\"block\":\"generated_quantities\"},{\"name\":\"kem\",\"type\":{\"name\":\"vector\",\"length\":" << n_met << "},\"block\":\"generated_quantities\"},{\"name\":\"U\",\"type\":{\"name\":\"vector\",\"length\":" << lentp << "},\"block\":\"generated_quantities\"},{\"name\":\"R\",\"type\":{\"name\":\"vector\",\"length\":" << lentp << "},\"block\":\"generated_quantities\"},{\"name\":\"D\",\"type\":{\"name\":\"vector\",\"length\":" << n_met << "},\"block\":\"generated_quantities\"},{\"name\":\"CGpred\",\"type\":{\"name\":\"matrix\",\"rows\":" << lentp << ",\"cols\":" << n_out << "},\"block\":\"generated_quantities\"},{\"name\":\"Cmetpred\",\"type\":{\"name\":\"matrix\",\"rows\":" << lentp << ",\"cols\":" << n_met << "},\"block\":\"generated_quantities\"}]";
    return s__.str();
    } // get_constrained_sizedtypes() 
    
  inline std::string get_unconstrained_sizedtypes() const {
    stringstream s__;
    s__ << "[{\"name\":\"CGobs_out\",\"type\":{\"name\":\"array\",\"length\":" << lentp << ",\"element_type\":{\"name\":\"array\",\"length\":" << n_out << ",\"element_type\":{\"name\":\"real\"}}},\"block\":\"generated_quantities\"},{\"name\":\"Cmet_out\",\"type\":{\"name\":\"array\",\"length\":" << lentp << ",\"element_type\":{\"name\":\"array\",\"length\":" << n_met << ",\"element_type\":{\"name\":\"real\"}}},\"block\":\"generated_quantities\"},{\"name\":\"Cexp_interpol\",\"type\":{\"name\":\"matrix\",\"rows\":" << lentp << ",\"cols\":" << n_exp << "},\"block\":\"generated_quantities\"},{\"name\":\"ku\",\"type\":{\"name\":\"vector\",\"length\":" << n_exp << "},\"block\":\"generated_quantities\"},{\"name\":\"ke\",\"type\":{\"name\":\"vector\",\"length\":" << n_out << "},\"block\":\"generated_quantities\"},{\"name\":\"km\",\"type\":{\"name\":\"vector\",\"length\":" << n_met << "},\"block\":\"generated_quantities\"},{\"name\":\"kem\",\"type\":{\"name\":\"vector\",\"length\":" << n_met << "},\"block\":\"generated_quantities\"},{\"name\":\"U\",\"type\":{\"name\":\"vector\",\"length\":" << lentp << "},\"block\":\"generated_quantities\"},{\"name\":\"R\",\"type\":{\"name\":\"vector\",\"length\":" << lentp << "},\"block\":\"generated_quantities\"},{\"name\":\"D\",\"type\":{\"name\":\"vector\",\"length\":" << n_met << "},\"block\":\"generated_quantities\"},{\"name\":\"CGpred\",\"type\":{\"name\":\"matrix\",\"rows\":" << lentp << ",\"cols\":" << n_out << "},\"block\":\"generated_quantities\"},{\"name\":\"Cmetpred\",\"type\":{\"name\":\"matrix\",\"rows\":" << lentp << ",\"cols\":" << n_met << "},\"block\":\"generated_quantities\"}]";
    return s__.str();
    } // get_unconstrained_sizedtypes() 
    
  
    // Begin method overload boilerplate
    template <typename RNG>
    inline void write_array(RNG& base_rng,
                            Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                            Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                            const bool emit_transformed_parameters = true,
                            const bool emit_generated_quantities = true,
                            std::ostream* pstream = nullptr) const {
      std::vector<double> vars_vec(vars.size());
      std::vector<int> params_i;
      write_array_impl(base_rng, params_r, params_i, vars_vec,
          emit_transformed_parameters, emit_generated_quantities, pstream);
      vars.resize(vars_vec.size());
      for (int i = 0; i < vars.size(); ++i) {
        vars.coeffRef(i) = vars_vec[i];
      }
    }
    template <typename RNG>
    inline void write_array(RNG& base_rng, std::vector<double>& params_r,
                            std::vector<int>& params_i,
                            std::vector<double>& vars,
                            bool emit_transformed_parameters = true,
                            bool emit_generated_quantities = true,
                            std::ostream* pstream = nullptr) const {
      write_array_impl(base_rng, params_r, params_i, vars, emit_transformed_parameters, emit_generated_quantities, pstream);
    }
    template <bool propto__, bool jacobian__, typename T_>
    inline T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
                       std::ostream* pstream = nullptr) const {
      Eigen::Matrix<int, -1, 1> params_i;
      return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
    }
    template <bool propto__, bool jacobian__, typename T__>
    inline T__ log_prob(std::vector<T__>& params_r,
                        std::vector<int>& params_i,
                        std::ostream* pstream = nullptr) const {
      return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
    }
  
    inline void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double, Eigen::Dynamic, 1>& params_r,
                         std::ostream* pstream = nullptr) const final {
      std::vector<double> params_r_vec(params_r.size());
      std::vector<int> params_i;
      transform_inits_impl(context, params_i, params_r_vec, pstream);
      params_r.resize(params_r_vec.size());
      for (int i = 0; i < params_r.size(); ++i) {
        params_r.coeffRef(i) = params_r_vec[i];
      }
    }
    inline void transform_inits(const stan::io::var_context& context,
                                std::vector<int>& params_i,
                                std::vector<double>& vars,
                                std::ostream* pstream = nullptr) const final {
      transform_inits_impl(context, params_i, vars, pstream);
    }        
};
}
using stan_model = model_TK_predict_namespace::model_TK_predict;
#ifndef USING_R
// Boilerplate
stan::model::model_base& new_model(
        stan::io::var_context& data_context,
        unsigned int seed,
        std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
stan::math::profile_map& get_stan_profile_data() {
  return model_TK_predict_namespace::profiles__;
}
#endif
#endif
